FROM quay.io/cilium/clang:b97f5b3d5c38da62fb009f21a53cd42aefd54a2f@sha256:e1c8ed0acd2e24ed05377f2861d8174af28e09bef3bbc79649c8eba165207df0 AS bpf-builder
WORKDIR /go/src/github.com/cilium/tetragon
RUN apt-get update
RUN apt-get install -y linux-libc-dev
COPY . ./
RUN make tetragon-bpf LOCAL_CLANG=1

FROM quay.io/cilium/cilium-bpftool@sha256:1832b32d118e7006ea2ce530b14ae5b28acd55fa15d8ab270f354736ae4f77e9 AS bpftool
COPY . ./


FROM docker.io/library/golang:1.25.5@sha256:20b91eda7a9627c127c0225b0d4e8ec927b476fa4130c6760928b849d769c149
RUN apt-get update -y &&    \
    apt-get upgrade -y &&   \
    apt-get install -y      \
	linux-libc-dev      \
	rpm2cpio            \
	cpio                \
	git                 \
	flex                \
	bison               \
	autoconf            \
	libelf-dev          \
	libcap-dev          \
	bc                  \
	netcat-traditional  \
	vim                 \
	file                \
	strace              \
	jq                  \
	less
RUN mkdir -p /etc/tetragon/tetragon.conf.d/ && \
    mkdir -p /etc/tetragon/tetragon.tp.d/
COPY --from=bpf-builder /go/src/github.com/cilium/tetragon/bpf/objs/*.o /var/lib/tetragon/
COPY --from=bpftool  /bin/bpftool /usr/bin/
WORKDIR /go/src/github.com/cilium/tetragon
COPY . ./
RUN make tetragon tetra test-compile contrib-progs


ENV TETRAGON_PROCFS=/procRoot/
# CMD ["sh", "-c", "/go/src/github.com/cilium/tetragon/tetragon --procfs=/procRoot/ --export-filename=/tmp/tetragon.log --metrics-server :2112 --verbose 4"]
CMD ["sh", "-c", "/go/src/github.com/cilium/tetragon/tetragon --procfs=/procRoot/"]
