FROM quay.io/cilium/clang:7ea8dd5b610a8864ce7b56e10ffeb61030a0c50e@sha256:02ad7cc1d08d85c027557099b88856945be5124b5c31aeabce326e7983e3913b as bpf-builder
WORKDIR /go/src/github.com/cilium/tetragon
RUN apt-get update
RUN apt-get install -y linux-libc-dev
COPY . ./
RUN make tetragon-bpf LOCAL_CLANG=1

FROM quay.io/cilium/cilium-bpftool AS bpftool
COPY . ./


FROM golang:1.19.2
RUN apt-get update -y &&    \
    apt-get upgrade -y &&   \
    apt-get install -y      \
	linux-libc-dev      \
	rpm2cpio            \
	cpio                \
	git                 \
	flex                \
	bison               \
	autoconf            \
	libelf-dev          \
	libcap-dev          \
	bc                  \
	netcat-traditional  \
	vim                 \
	file                \
	strace              \
	jq                  \
	less
COPY --from=bpf-builder /go/src/github.com/cilium/tetragon/bpf/objs/*.o /var/lib/tetragon/
COPY --from=bpftool  /bin/bpftool /usr/bin/
WORKDIR /go/src/github.com/cilium/tetragon
COPY . ./
RUN make tetragon tetra test-compile contrib-progs


ENV TETRAGON_PROCFS=/procRoot/
# CMD ["sh", "-c", "/go/src/github.com/cilium/tetragon/tetragon --procfs=/procRoot/ --export-filename=/tmp/tetragon.log --metrics-server :2112 --verbose 4"]
CMD ["sh", "-c", "/go/src/github.com/cilium/tetragon/tetragon --procfs=/procRoot/"]
