FROM docker.io/library/ubuntu:22.04@sha256:0bced47fffa3361afa981854fcabcd4577cd43cebbb808cea2b1f33a3dd7f508

RUN apt-get -y update
RUN apt-get -y install clang-format-14
RUN ln -s /bin/clang-format-14 /bin/clang-format

USER 1000
WORKDIR /tetragon

ENTRYPOINT ["clang-format"]
CMD ["--help"]
