FROM docker.io/library/ubuntu:22.10@sha256:e322f4808315c387868a9135beeb11435b5b83130a8599fd7d0014452c34f489

RUN apt-get -y update
RUN apt-get -y install clang-format-14
RUN ln -s /bin/clang-format-14 /bin/clang-format

USER 1000
WORKDIR /tetragon

ENTRYPOINT ["clang-format"]
CMD ["--help"]
