FROM docker.io/library/ubuntu:22.10@sha256:e322f4808315c387868a9135beeb11435b5b83130a8599fd7d0014452c34f489
ARG VERSION=1:15.0.7-0ubuntu0.22.04.1
RUN apt-get update
RUN apt-get -y upgrade
RUN apt-cache search clang
RUN apt show clang-15
RUN apt-get install -y --no-install-recommends clang-15=$VERSION libclang-common-15-dev=$VERSION libclang-cpp15=$VERSION libllvm15=$VERSION llvm-15-linker-tools=$VERSION libclang1-15=$VERSION llvm-15=$VERSION llvm-15-runtime=$VERSION llvm-15-linker-tools=$VERSION make
RUN ln -vsnf /usr/lib/llvm-15/bin/clang /usr/bin/clang
RUN ln -vsnf /usr/lib/llvm-15/bin/llc /usr/bin/llc
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
