// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	ciliumiov1alpha1 "github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/typed/cilium.io/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeTracingPolicies implements TracingPolicyInterface
type fakeTracingPolicies struct {
	*gentype.FakeClientWithList[*v1alpha1.TracingPolicy, *v1alpha1.TracingPolicyList]
	Fake *FakeCiliumV1alpha1
}

func newFakeTracingPolicies(fake *FakeCiliumV1alpha1) ciliumiov1alpha1.TracingPolicyInterface {
	return &fakeTracingPolicies{
		gentype.NewFakeClientWithList[*v1alpha1.TracingPolicy, *v1alpha1.TracingPolicyList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("tracingpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("TracingPolicy"),
			func() *v1alpha1.TracingPolicy { return &v1alpha1.TracingPolicy{} },
			func() *v1alpha1.TracingPolicyList { return &v1alpha1.TracingPolicyList{} },
			func(dst, src *v1alpha1.TracingPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.TracingPolicyList) []*v1alpha1.TracingPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.TracingPolicyList, items []*v1alpha1.TracingPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
