// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRuntimeSecurityPolicies implements RuntimeSecurityPolicyInterface
type FakeRuntimeSecurityPolicies struct {
	Fake *FakeCiliumV1alpha1
}

var runtimesecuritypoliciesResource = v1alpha1.SchemeGroupVersion.WithResource("runtimesecuritypolicies")

var runtimesecuritypoliciesKind = v1alpha1.SchemeGroupVersion.WithKind("RuntimeSecurityPolicy")

// Get takes name of the runtimeSecurityPolicy, and returns the corresponding runtimeSecurityPolicy object, and an error if there is any.
func (c *FakeRuntimeSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(runtimesecuritypoliciesResource, name), &v1alpha1.RuntimeSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeSecurityPolicy), err
}

// List takes label and field selectors, and returns the list of RuntimeSecurityPolicies that match those selectors.
func (c *FakeRuntimeSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeSecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(runtimesecuritypoliciesResource, runtimesecuritypoliciesKind, opts), &v1alpha1.RuntimeSecurityPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RuntimeSecurityPolicyList{ListMeta: obj.(*v1alpha1.RuntimeSecurityPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.RuntimeSecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested runtimeSecurityPolicies.
func (c *FakeRuntimeSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(runtimesecuritypoliciesResource, opts))
}

// Create takes the representation of a runtimeSecurityPolicy and creates it.  Returns the server's representation of the runtimeSecurityPolicy, and an error, if there is any.
func (c *FakeRuntimeSecurityPolicies) Create(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.CreateOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(runtimesecuritypoliciesResource, runtimeSecurityPolicy), &v1alpha1.RuntimeSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeSecurityPolicy), err
}

// Update takes the representation of a runtimeSecurityPolicy and updates it. Returns the server's representation of the runtimeSecurityPolicy, and an error, if there is any.
func (c *FakeRuntimeSecurityPolicies) Update(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.UpdateOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(runtimesecuritypoliciesResource, runtimeSecurityPolicy), &v1alpha1.RuntimeSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeSecurityPolicy), err
}

// Delete takes name of the runtimeSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeRuntimeSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(runtimesecuritypoliciesResource, name, opts), &v1alpha1.RuntimeSecurityPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuntimeSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(runtimesecuritypoliciesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RuntimeSecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched runtimeSecurityPolicy.
func (c *FakeRuntimeSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(runtimesecuritypoliciesResource, name, pt, data, subresources...), &v1alpha1.RuntimeSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RuntimeSecurityPolicy), err
}
