#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright Authors of Tetragon

set -euo pipefail

agent_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
env_file=$agent_dir/build/java-monitoring.env

if [[ ! -f $env_file ]]; then
	echo "Missing $env_file" >&2
	echo "Run $agent_dir/run-tetragon.sh first." >&2
	exit 1
fi

# The file is generated by run-tetragon.sh and contains shell-escaped paths.
# shellcheck disable=SC1090
source "$env_file"

monitor_class=${JAVA_MONITOR_CLASS-sample.Sample}
monitor_method=${JAVA_MONITOR_METHOD-work}
agent_argument="class=$monitor_class,method=$monitor_method"
pin_path=/sys/fs/bpf/tetragon/tg_java_urb

if ! sudo test -e "$pin_path"; then
	echo "The Java producer map is not available at $pin_path" >&2
	echo "Keep run-tetragon.sh running in another terminal and retry." >&2
	exit 1
fi

echo "Monitoring ${monitor_class:-*}#${monitor_method:-*}"
if [[ $JAVA_MONITOR_RUNTIME == native ]]; then
	exec sudo "$JAVA_MONITOR_JAVA_HOME/bin/java" \
		--enable-native-access=ALL-UNNAMED \
		"-javaagent:$JAVA_MONITOR_AGENT_DIR/tetragon-java-monitoring-agent.jar=$agent_argument" \
		-cp "$JAVA_MONITOR_AGENT_DIR/build/sample:$JAVA_MONITOR_ASM_JAR:$JAVA_MONITOR_ASM_COMMONS_JAR" \
		sample.Sample "$@"
fi

if [[ $JAVA_MONITOR_RUNTIME != docker ]]; then
	echo "Unknown Java runtime in $env_file: $JAVA_MONITOR_RUNTIME" >&2
	exit 1
fi

# Host PID namespace visibility is required because the prototype records the
# PID reported by the JVM without translating container PID namespaces.
exec sudo docker run --rm --privileged --pid=host \
	-v /sys/fs/bpf:/sys/fs/bpf \
	-v "$JAVA_MONITOR_AGENT_DIR:/agent:ro" \
	-v "$JAVA_MONITOR_ASM_JAR:/deps/asm.jar:ro" \
	-v "$JAVA_MONITOR_ASM_COMMONS_JAR:/deps/asm-commons.jar:ro" \
	-w /agent \
	"$JAVA_MONITOR_JDK_IMAGE" \
	java --enable-native-access=ALL-UNNAMED \
	"-javaagent:/agent/tetragon-java-monitoring-agent.jar=$agent_argument" \
	-cp /agent/build/sample:/deps/asm.jar:/deps/asm-commons.jar \
	sample.Sample "$@"
