// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	scheme "github.com/cilium/tetragon/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RuntimeSecurityPoliciesGetter has a method to return a RuntimeSecurityPolicyInterface.
// A group's client should implement this interface.
type RuntimeSecurityPoliciesGetter interface {
	RuntimeSecurityPolicies() RuntimeSecurityPolicyInterface
}

// RuntimeSecurityPolicyInterface has methods to work with RuntimeSecurityPolicy resources.
type RuntimeSecurityPolicyInterface interface {
	Create(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.CreateOptions) (*v1alpha1.RuntimeSecurityPolicy, error)
	Update(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.UpdateOptions) (*v1alpha1.RuntimeSecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RuntimeSecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RuntimeSecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeSecurityPolicy, err error)
	RuntimeSecurityPolicyExpansion
}

// runtimeSecurityPolicies implements RuntimeSecurityPolicyInterface
type runtimeSecurityPolicies struct {
	client rest.Interface
}

// newRuntimeSecurityPolicies returns a RuntimeSecurityPolicies
func newRuntimeSecurityPolicies(c *CiliumV1alpha1Client) *runtimeSecurityPolicies {
	return &runtimeSecurityPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the runtimeSecurityPolicy, and returns the corresponding runtimeSecurityPolicy object, and an error if there is any.
func (c *runtimeSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	result = &v1alpha1.RuntimeSecurityPolicy{}
	err = c.client.Get().
		Resource("runtimesecuritypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RuntimeSecurityPolicies that match those selectors.
func (c *runtimeSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RuntimeSecurityPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RuntimeSecurityPolicyList{}
	err = c.client.Get().
		Resource("runtimesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested runtimeSecurityPolicies.
func (c *runtimeSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("runtimesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a runtimeSecurityPolicy and creates it.  Returns the server's representation of the runtimeSecurityPolicy, and an error, if there is any.
func (c *runtimeSecurityPolicies) Create(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.CreateOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	result = &v1alpha1.RuntimeSecurityPolicy{}
	err = c.client.Post().
		Resource("runtimesecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(runtimeSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a runtimeSecurityPolicy and updates it. Returns the server's representation of the runtimeSecurityPolicy, and an error, if there is any.
func (c *runtimeSecurityPolicies) Update(ctx context.Context, runtimeSecurityPolicy *v1alpha1.RuntimeSecurityPolicy, opts v1.UpdateOptions) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	result = &v1alpha1.RuntimeSecurityPolicy{}
	err = c.client.Put().
		Resource("runtimesecuritypolicies").
		Name(runtimeSecurityPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(runtimeSecurityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the runtimeSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *runtimeSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("runtimesecuritypolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *runtimeSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("runtimesecuritypolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched runtimeSecurityPolicy.
func (c *runtimeSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RuntimeSecurityPolicy, err error) {
	result = &v1alpha1.RuntimeSecurityPolicy{}
	err = c.client.Patch(pt).
		Resource("runtimesecuritypolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
