// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// PodInfoListerExpansion allows custom methods to be added to
// PodInfoLister.
type PodInfoListerExpansion interface{}

// PodInfoNamespaceListerExpansion allows custom methods to be added to
// PodInfoNamespaceLister.
type PodInfoNamespaceListerExpansion interface{}

// RuntimeSecurityPolicyListerExpansion allows custom methods to be added to
// RuntimeSecurityPolicyLister.
type RuntimeSecurityPolicyListerExpansion interface{}

// TracingPolicyListerExpansion allows custom methods to be added to
// TracingPolicyLister.
type TracingPolicyListerExpansion interface{}

// TracingPolicyNamespacedListerExpansion allows custom methods to be added to
// TracingPolicyNamespacedLister.
type TracingPolicyNamespacedListerExpansion interface{}

// TracingPolicyNamespacedNamespaceListerExpansion allows custom methods to be added to
// TracingPolicyNamespacedNamespaceLister.
type TracingPolicyNamespacedNamespaceListerExpansion interface{}
