// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RuntimeSecurityPolicyLister helps list RuntimeSecurityPolicies.
// All objects returned here must be treated as read-only.
type RuntimeSecurityPolicyLister interface {
	// List lists all RuntimeSecurityPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RuntimeSecurityPolicy, err error)
	// Get retrieves the RuntimeSecurityPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RuntimeSecurityPolicy, error)
	RuntimeSecurityPolicyListerExpansion
}

// runtimeSecurityPolicyLister implements the RuntimeSecurityPolicyLister interface.
type runtimeSecurityPolicyLister struct {
	indexer cache.Indexer
}

// NewRuntimeSecurityPolicyLister returns a new RuntimeSecurityPolicyLister.
func NewRuntimeSecurityPolicyLister(indexer cache.Indexer) RuntimeSecurityPolicyLister {
	return &runtimeSecurityPolicyLister{indexer: indexer}
}

// List lists all RuntimeSecurityPolicies in the indexer.
func (s *runtimeSecurityPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.RuntimeSecurityPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RuntimeSecurityPolicy))
	})
	return ret, err
}

// Get retrieves the RuntimeSecurityPolicy from the index for a given name.
func (s *runtimeSecurityPolicyLister) Get(name string) (*v1alpha1.RuntimeSecurityPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("runtimesecuritypolicy"), name)
	}
	return obj.(*v1alpha1.RuntimeSecurityPolicy), nil
}
