// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	ciliumiov1alpha1 "github.com/cilium/tetragon/pkg/k8s/apis/cilium.io/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// TracingPolicyLister helps list TracingPolicies.
// All objects returned here must be treated as read-only.
type TracingPolicyLister interface {
	// List lists all TracingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov1alpha1.TracingPolicy, err error)
	// Get retrieves the TracingPolicy from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov1alpha1.TracingPolicy, error)
	TracingPolicyListerExpansion
}

// tracingPolicyLister implements the TracingPolicyLister interface.
type tracingPolicyLister struct {
	listers.ResourceIndexer[*ciliumiov1alpha1.TracingPolicy]
}

// NewTracingPolicyLister returns a new TracingPolicyLister.
func NewTracingPolicyLister(indexer cache.Indexer) TracingPolicyLister {
	return &tracingPolicyLister{listers.New[*ciliumiov1alpha1.TracingPolicy](indexer, ciliumiov1alpha1.Resource("tracingpolicy"))}
}
