{{- if and .Values.tetragon.enabled .Values.tetragon.grpc.tls.enabled .Values.tetragon.grpc.tls.auto.enabled (eq .Values.tetragon.grpc.tls.auto.method "cronJob") (not .Values.tetragon.grpc.tls.server.existingSecret) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tetragon.name" . }}-certgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
    app.kubernetes.io/component: certgen
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tetragon.name" . }}-certgen
subjects:
  - kind: ServiceAccount
    name: {{ include "tetragon.name" . }}-certgen
    namespace: {{ .Release.Namespace }}
{{- end }}
