{{- if and .Values.tetragon.enabled .Values.tetragon.grpc.tls.enabled .Values.tetragon.grpc.tls.auto.enabled (eq .Values.tetragon.grpc.tls.auto.method "cronJob") (not .Values.tetragon.grpc.tls.server.existingSecret) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tetragon.name" . }}-certgen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
    app.kubernetes.io/component: certgen
{{- end }}
