{{- if and .Values.tetragon.enabled .Values.tetragon.grpc.tls.enabled .Values.tetragon.grpc.tls.auto.enabled (eq .Values.tetragon.grpc.tls.auto.method "certmanager") (not .Values.tetragon.grpc.tls.server.existingSecret) -}}
{{- if not .Values.tetragon.grpc.tls.auto.certManagerIssuerRef -}}
{{- fail "tetragon.grpc.tls.auto.certManagerIssuerRef must be set when auto.method is certmanager" -}}
{{- end -}}
{{- $cn := include "tetragon.grpcTls.commonName" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "tetragon.grpcTlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tetragon.labels" . | nindent 4 }}
    tetragon.cilium.io/tls-method: certmanager
spec:
  secretName: {{ include "tetragon.grpcTlsSecretName" . }}
  commonName: {{ $cn | quote }}
  dnsNames:
    {{- include "tetragon.grpcTls.dnsNames" . | nindent 4 }}
  {{- with .Values.tetragon.grpc.tls.server.extraIpAddresses }}
  ipAddresses:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  duration: {{ printf "%dh0m0s" (mul .Values.tetragon.grpc.tls.auto.certValidityDuration 24) | quote }}
  privateKey:
    rotationPolicy: Always
  isCA: false
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    {{- toYaml .Values.tetragon.grpc.tls.auto.certManagerIssuerRef | nindent 4 }}
{{- end }}
