//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//

// Code generated by protoc-gen-go-tetragon. DO NOT EDIT

package filters

import (
	fmt "fmt"
	fgs "github.com/cilium/tetragon/api/v1/fgs"
	reflect "reflect"
)

func OpCodeForEventType(eventType fgs.EventType) (reflect.Type, error) {
	var opCode reflect.Type
	switch eventType {
	case fgs.EventType_PROCESS_EXEC:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_ProcessExec{})
	case fgs.EventType_PROCESS_EXIT:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_ProcessExit{})
	case fgs.EventType_PROCESS_KPROBE:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_ProcessKprobe{})
	case fgs.EventType_PROCESS_TRACEPOINT:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_ProcessTracepoint{})
	case fgs.EventType_PROCESS_DNS:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_ProcessDns{})
	case fgs.EventType_TEST:
		opCode = reflect.TypeOf(&fgs.GetEventsResponse_Test{})
	default:
		return nil, fmt.Errorf("Unknown EventType %s", eventType)
	}
	return opCode, nil
}
