**

!go.mod
!go.sum

!vendor/
!vendor/**

!pkg/
!pkg/**

!contrib/
!contrib/tester-progs/
!contrib/tester-progs/Makefile
!contrib/tester-progs/*.c
!contrib/tester-progs/*.h
!contrib/tester-progs/go/
!contrib/tester-progs/go/**
