//  Copyright (C) Isovalent, Inc. - All Rights Reserved.
//
//  NOTICE: All information contained herein is, and remains the property of
//  Isovalent Inc and its suppliers, if any. The intellectual and technical
//  concepts contained herein are proprietary to Isovalent Inc and its suppliers
//  and may be covered by U.S. and Foreign Patents, patents in process, and are
//  protected by trade secret or copyright law.  Dissemination of this information
//  or reproduction of this material is strictly forbidden unless prior written
//  permission is obtained from Isovalent Inc.
//

// Code generated by protoc-gen-go-tetragon. DO NOT EDIT

package helpers

import (
	fmt "fmt"
	fgs "github.com/cilium/tetragon/api/v1/fgs"
)

type event interface {
	// Represents a generic Tetragon event
}
type response interface {
	// Represents a generic Tetragon gRPC response
}

// EventTypeString returns an event's type as a string
func EventTypeString(event event) (string, error) {
	if event == nil {
		return "", fmt.Errorf("Event is nil")
	}
	switch event.(type) {
	case *fgs.GetEventsResponse_ProcessExec:
		return fgs.EventType_PROCESS_EXEC.String(), nil
	case *fgs.GetEventsResponse_ProcessExit:
		return fgs.EventType_PROCESS_EXIT.String(), nil
	case *fgs.GetEventsResponse_ProcessKprobe:
		return fgs.EventType_PROCESS_KPROBE.String(), nil
	case *fgs.GetEventsResponse_ProcessTracepoint:
		return fgs.EventType_PROCESS_TRACEPOINT.String(), nil
	case *fgs.GetEventsResponse_Test:
		return fgs.EventType_TEST.String(), nil
	case *fgs.GetEventsResponse_ProcessDns:
		return fgs.EventType_PROCESS_DNS.String(), nil

	}
	return "", fmt.Errorf("Unhandled event type %T", event)
}

// EventGetProcess gets the process field for an event if it exists
func EventGetProcess(event event) *fgs.Process {
	if event == nil {
		return nil
	}
	switch ev := event.(type) {
	case *fgs.GetEventsResponse_ProcessExec:
		return ev.ProcessExec.Process
	case *fgs.GetEventsResponse_ProcessExit:
		return ev.ProcessExit.Process
	case *fgs.GetEventsResponse_ProcessKprobe:
		return ev.ProcessKprobe.Process
	case *fgs.GetEventsResponse_ProcessTracepoint:
		return ev.ProcessTracepoint.Process
	case *fgs.GetEventsResponse_ProcessDns:
		return ev.ProcessDns.Process

	}
	return nil
}

// ResponseGetProcess gets the process field for a response if it exists
func ResponseGetProcess(response response) *fgs.Process {
	if response == nil {
		return nil
	}
	switch res := response.(type) {
	case *fgs.GetEventsResponse:
		return EventGetProcess(res.Event)
	}
	return nil
}

// EventGetParent gets the parent field for an event if it exists
func EventGetParent(event event) *fgs.Process {
	if event == nil {
		return nil
	}
	switch ev := event.(type) {
	case *fgs.GetEventsResponse_ProcessExec:
		return ev.ProcessExec.Parent
	case *fgs.GetEventsResponse_ProcessExit:
		return ev.ProcessExit.Parent
	case *fgs.GetEventsResponse_ProcessKprobe:
		return ev.ProcessKprobe.Parent
	case *fgs.GetEventsResponse_ProcessTracepoint:
		return ev.ProcessTracepoint.Parent

	}
	return nil
}

// ResponseGetParent gets the parent field for a response if it exists
func ResponseGetParent(response response) *fgs.Process {
	if response == nil {
		return nil
	}
	switch res := response.(type) {
	case *fgs.GetEventsResponse:
		return EventGetParent(res.Event)
	}
	return nil
}
