// Code generated by goabi-gen; DO NOT EDIT.

// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

package tracing

var goABIKnownFuncs = map[string][]int{
	"net/http.ServeContent":           {0, 2, 3, 5, 8},
	"net/http.ServeFile":              {0, 2, 3},
	"net/http.Get":                    {0},
	"net/http.NewRequest":             {0, 2, 4},
	"path/filepath.Clean":             {0},
	"strings.ToUpper":                 {0},
	"os.Open":                         {0},
	"os.OpenFile":                     {0, 2, 3},
	"os.ReadFile":                     {0},
	"os.WriteFile":                    {0, 2, 5},
	"text/template.(*Template).Parse": {0, 1},
	"html/template.(*Template).Parse": {0, 1},
	"github.com/cilium/tetragon/pkg/sensors/tracing/goabitest.ReportLenForABI": {0},
}
