apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "fentry"
spec:
  fentries:
  - call: "tcp_connect"
    syscall: false
    return: true
    args:
    - index: 0
      type: "sock"
    returnArg:
      index: 0
      type: "int"
  - call: "tcp_close"
    syscall: false
    args:
    - index: 0
      type: "sock"
