apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "usdts"
spec:
  options:
    - name: "disable-uprobe-multi"
      value: "1"
  usdts:
  - path: "/home/jolsa/tetragon/contrib/tester-progs/usdt"
    names:
      - provider: "test"
        name: "usdt0"
