// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Tetragon

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TracingPolicyListerExpansion allows custom methods to be added to
// TracingPolicyLister.
type TracingPolicyListerExpansion interface{}
