// Copyright (c) 2021 Isovalent

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TracingPolicyListerExpansion allows custom methods to be added to
// TracingPolicyLister.
type TracingPolicyListerExpansion interface{}
