name: BPF Unit Tests
on:
  pull_request:
    paths:
      - 'bpf/**'
      - '.github/workflows/bpf-unit-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'bpf/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm64 ]
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.27.1'

    - name: Install LLVM 22
      run: |
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
          | sudo gpg --dearmor -o /usr/share/keyrings/llvm.gpg
        echo "deb [signed-by=/usr/share/keyrings/llvm.gpg] https://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-22 main" \
          | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt-get update
        sudo apt-get -y install clang-22 llvm-22
        sudo ln -vsnf /usr/lib/llvm-22/bin/clang /usr/bin/clang
        sudo ln -vsnf /usr/lib/llvm-22/bin/llc /usr/bin/llc
        clang --version

    - name: Run BPF unit test
      run: make bpf-test BPFGOTESTFLAGS="-v"
