name: Packages e2e Tests

on:
  pull_request:
    paths-ignore:
    - "**.md"
    - 'docs/**'

jobs:
  standalone-tarball-builds:
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-22.04-arm') || 'ubuntu-22.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Getting version tag
        id: tag
        run: echo "tag=$(make version)" >> $GITHUB_OUTPUT

      - name: Generate Tetragon Tarball
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          make tarball
          mkdir upload/
          mv ./build/${{ matrix.arch }}/linux-tarball/tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}.tar.gz ./upload/

      # Cache tarball releases for later
      - name: Save tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}.tar.gz Tarball
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}
          path: upload/
          retention-days: 1

  standalone-tarball-tests:
    needs: [standalone-tarball-builds]
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-22.04-arm') || 'ubuntu-22.04' }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            match_arch: x86-64
          - arch: arm64
            match_arch: arm64
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Getting version tag
        id: tag
        run: echo "tag=$(make version)" >> $GITHUB_OUTPUT

      - name: Retrieve tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}.tar.gz
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}
          path: ./download

      - name: Move tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}.tar.gz to build
        run: |
          mkdir -p ./build/${{ matrix.arch }}/
          mv ./download ./build/${{ matrix.arch }}/linux-tarball

      - name: Copy bpf.yaml tracing policy to /etc/tetragon/tetragon.tp.d/
        run: |
          sudo mkdir -p /etc/tetragon/tetragon.tp.d/
          sudo cp examples/tracingpolicy/bpf.yaml /etc/tetragon/tetragon.tp.d/bpf.yaml

      - name: Install Tetragon Tarball
        run: |
          tar zxvf tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}.tar.gz
          sudo ./tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}/install.sh
        working-directory: ./build/${{ matrix.arch }}/linux-tarball/

      - name: Wait for Tetragon service
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_wait_seconds: 5
          retry_on: error
          command: |
            # Ensure that default native builds work
            file /usr/local/bin/tetragon | grep ${{ matrix.match_arch }} -
            sudo systemctl is-active tetragon
            sudo tetra status

      - name: Check Tetragon startup logs
        run: sudo journalctl -b -u tetragon --no-pager

      - name: Test Tetragon
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_seconds: 30
          max_attempts: 5
          retry_wait_seconds: 5
          retry_on: error
          command: |
            sudo tetra status
            test $(stat -c %a /var/run/tetragon/tetragon.sock) -eq "660"
            sudo tetra bugtool
            sudo tetra tracingpolicy list | grep bpf -
            sudo tetra tracingpolicy add examples/tracingpolicy/tcp-connect.yaml
            sudo tetra tracingpolicy list | grep connect -
            sudo grep "tetra" /var/log/tetragon/tetragon.log

      - name: Setup Tetragon with a different tracing-policy-dir
        run: |
          sudo systemctl stop tetragon
          sudo mkdir -p /opt/tetragon.tp.d/
          sudo cp examples/tracingpolicy/bpf.yaml /opt/tetragon.tp.d/bpf.yaml
          echo "/opt/tetragon.tp.d/" | sudo tee /etc/tetragon/tetragon.conf.d/tracing-policy-dir
          echo "localhost:8118" | sudo tee /etc/tetragon/tetragon.conf.d/gops-address
          sudo systemctl start tetragon

      - name: Test Tetragon with a different tracing-policy-dir
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08 # v3.0.2
        with:
          timeout_seconds: 60
          max_attempts: 5
          retry_wait_seconds: 5
          retry_on: error
          command: |
            sudo systemctl is-active tetragon
            sudo tetra status
            sudo grep "tetra" /var/log/tetragon/tetragon.log
            sudo tetra tracingpolicy list | grep bpf -
            sudo tetra bugtool 2>&1 | grep "Successfully dumped gops pprof.*profile=heap" -

      - name: Uninstall Tetragon Tarball
        run: |
          sudo ./tetragon-${{ steps.tag.outputs.tag }}-${{ matrix.arch }}/uninstall.sh
        working-directory: ./build/${{ matrix.arch }}/linux-tarball/
