name: Run veristat
on:
  push:
    branches:
      - main
      - v*
    paths:
      - 'bpf/**'
  pull_request:
    paths:
      - 'bpf/**'

jobs:
  veristat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build BPF programs
        run: make tetragon-bpf

      - name: Run veristat
        uses: mtardy/veristat-action@f8aaf0aff94a274fea229c37e1165b3083d43611 # v1.0.1
        with:
          programs: "bpf/objs/*.o"
