name: Run veristat
on:
  push:
    branches:
      - main
      - v*
    paths:
      - 'bpf/**'
  pull_request:
    paths:
      - 'bpf/**'

jobs:
  veristat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build BPF programs
        run: make tetragon-bpf

      - name: Run veristat
        uses: mtardy/veristat-action@a405c518108546e1c374fc79b5dcfd3bf5daacef # v1.0.2
        with:
          programs: "bpf/objs/*.o"
