name: Run veristat compare
on:
  pull_request:
    paths:
      - 'bpf/**'

jobs:
  veristat-compare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: branch

      - name: Checkout base ref
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: base
          ref: ${{ github.base_ref }}

      - name: Build BPF programs
        run: |
          make -C branch tetragon-bpf
          make -C base tetragon-bpf

      - name: Run veristat comparison
        uses: mtardy/veristat-action@a405c518108546e1c374fc79b5dcfd3bf5daacef # v1.0.2
        with:
          compare: true
          baseline-programs: "base/bpf/objs/*.o"
          comparison-programs: "branch/bpf/objs/*.o"
